export type BuilderInput = {
  title: string;
  author: string;
  vibe: string;
  supabaseUrl: string;
  supabaseAnonKey: string;
  studioPassword: string;
  coverFileName: string;
  companyLogoFileName?: string;
};

export type ThemeData = {
  tagline: string;
  subtitle: string;
  cta: string;
  introQuote: string;
  introAttribution: string;
  episodeLabel: string;
  emptyState: string;
  studioTitle: string;
  addEpisodeLabel: string;
  manageEpisodeLabel: string;
  fontHeading: string;
  fontBody: string;
  palette: {
    bg: string;
    surface: string;
    text: string;
    muted: string;
    accent: string;
    accent2: string;
    danger: string;
  };
  motifs?: string[];
};

export function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "novel";
}

function esc(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function js(value: string) {
  return JSON.stringify(value);
}

export function namesForTitle(title: string) {
  const slug = slugify(title);
  return {
    slug,
    bucket: `${slug}-pdfs`,
    table: `${slug.replace(/-/g, "_")}_episodes`,
    folder: `${slug}-website`,
  };
}

export function generateSetupReadme(input: BuilderInput) {
  const names = namesForTitle(input.title);
  return `# ${input.title} Website Setup

This folder contains:
- index.html
- ${input.coverFileName}
- ${input.companyLogoFileName || "soul-logo.png"}

## Supabase Values Used

Project URL:
${input.supabaseUrl}

Storage bucket:
${names.bucket}

Database table:
${names.table}

## 1. Create The Episodes Table

Open Supabase SQL Editor and run:

create table if not exists public.${names.table} (
  id bigint generated by default as identity primary key,
  num integer not null unique,
  title text not null,
  part text,
  pdf_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.${names.table} enable row level security;

create policy "Anyone can read ${names.table}"
on public.${names.table}
for select
using (true);

create policy "Anyone can insert ${names.table}"
on public.${names.table}
for insert
with check (true);

create policy "Anyone can update ${names.table}"
on public.${names.table}
for update
using (true)
with check (true);

create policy "Anyone can delete ${names.table}"
on public.${names.table}
for delete
using (true);

## 2. Create Storage Bucket

In Supabase Storage, create a public bucket named:
${names.bucket}

Then add storage policies that allow public read plus upload/delete for this bucket.
For a public static novel site, this keeps the Writer's Studio flow simple.

## 3. Host The Site

Upload index.html, ${input.coverFileName}, and ${input.companyLogoFileName || "soul-logo.png"} together to the same folder on your static host.
Do not rename the cover file unless you also update the reference inside index.html.

## Security Note

This v1 generated site follows the original template style: it uses a password gate in browser JavaScript and Supabase anon access. It is simple and practical for a public serial site, but it is not strong admin security. For private production admin access, add real authentication later.
`;
}

export function generateNovelHtml(input: BuilderInput, theme: ThemeData) {
  const names = namesForTitle(input.title);
  const title = esc(input.title);
  const author = esc(input.author);
  const logoFile = esc(input.companyLogoFileName || "soul-logo.png");
  const p = theme.palette;
  const motifs = esc((theme.motifs || []).slice(0, 3).join(" / "));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;700&family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
<style>
:root{
  --bg:${esc(p.bg)};--surface:${esc(p.surface)};--text:${esc(p.text)};--muted:${esc(p.muted)};
  --accent:${esc(p.accent)};--accent2:${esc(p.accent2)};--danger:${esc(p.danger)};
  --heading:"${esc(theme.fontHeading || "Cormorant Garamond")}",serif;--body:"${esc(theme.fontBody || "Inter")}",sans-serif;
}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--text);font-family:var(--body);min-height:100vh}
button,input{font:inherit}
button{cursor:pointer}
.hero{min-height:92vh;display:grid;align-items:end;position:relative;overflow:hidden;padding:2rem}
.hero-bg{position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.24)),url("./${esc(input.coverFileName)}") center/cover no-repeat;transform:scale(1.02)}
.grain{position:absolute;inset:0;opacity:.15;background-image:radial-gradient(circle at 20% 20%,var(--accent),transparent 18%),radial-gradient(circle at 80% 30%,var(--accent2),transparent 14%)}
.hero-content{position:relative;z-index:1;max-width:960px;width:100%;padding-bottom:7vh}
.tagline{text-transform:uppercase;letter-spacing:.16em;color:var(--accent2);font-size:.8rem;font-weight:700}
h1{font-family:var(--heading);font-size:clamp(4rem,12vw,10rem);line-height:.82;margin:1rem 0;letter-spacing:0}
.subtitle{max-width:680px;color:var(--muted);font-size:clamp(1rem,2.2vw,1.35rem);line-height:1.6}
.hero-actions{display:flex;gap:1rem;flex-wrap:wrap;margin-top:2rem}
.btn{border:1px solid color-mix(in srgb,var(--accent),white 8%);background:var(--accent);color:#120d0a;border-radius:7px;padding:.9rem 1.1rem;font-weight:800;text-decoration:none}
.btn.secondary{background:rgba(255,255,255,.06);color:var(--text);border-color:rgba(255,255,255,.18)}
.quote-strip{padding:2.5rem 1.5rem;background:var(--surface);border-block:1px solid rgba(255,255,255,.1);text-align:center}
.quote-strip blockquote{font-family:var(--heading);font-size:clamp(1.8rem,4vw,3.5rem);line-height:1.05;margin:0 auto;max-width:980px}
.quote-strip p{color:var(--muted)}
.episodes{padding:5rem 1.5rem;max-width:1050px;margin:0 auto}
.section-head{display:flex;justify-content:space-between;gap:1rem;align-items:end;margin-bottom:1.5rem}
.section-head h2{font-family:var(--heading);font-size:clamp(2.4rem,6vw,5rem);margin:0}
.motifs{color:var(--muted);text-align:right}
.ep-list{display:grid;gap:.85rem}
.ep-empty,.ep-item{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.045);border-radius:8px;padding:1rem}
.ep-item{display:grid;grid-template-columns:auto 1fr auto;gap:1rem;align-items:center;transition:.2s ease}
.ep-item:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--accent),white 15%)}
.ep-num{color:var(--accent2);font-weight:800;text-transform:uppercase;font-size:.8rem}
.ep-title{font-weight:800}
.ep-part{color:var(--muted);font-size:.92rem;margin-top:.2rem}
.brand-footer{padding:2rem 1.5rem;color:var(--muted);text-align:center;border-top:1px solid rgba(255,255,255,.1);display:flex;align-items:center;justify-content:center;gap:.7rem;flex-wrap:wrap}
.brand-footer img{width:34px;height:34px;object-fit:contain;opacity:.72;filter:drop-shadow(0 0 10px color-mix(in srgb,var(--accent2),transparent 35%))}
.reader-overlay,.studio-overlay,.studio-panel{position:fixed;inset:0;z-index:50;display:none;background:rgba(0,0,0,.92)}
.reader-overlay.open,.studio-overlay.open,.studio-panel.open{display:flex}
.reader-overlay{flex-direction:column}
.reader-topbar,.studio-header{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem;border-bottom:1px solid rgba(255,255,255,.12);background:var(--surface)}
.reader-close,.studio-exit,.reader-nav,.studio-btn,.s-submit,.manage-del{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.06);color:var(--text);border-radius:7px;padding:.7rem .9rem;font-weight:800}
.reader-stage{position:relative;flex:1;display:grid;place-items:center;padding:1rem 1rem 5rem;overflow:auto}
#pdfCanvas{max-width:100%;background:white;border-radius:6px;box-shadow:0 20px 70px rgba(0,0,0,.45)}
.reader-controls{position:absolute;left:50%;bottom:1rem;transform:translateX(-50%);display:flex;align-items:center;gap:.8rem;background:var(--surface);border:1px solid rgba(255,255,255,.14);border-radius:8px;padding:.6rem}
.reader-loading{position:absolute;color:var(--muted)}
.studio-overlay{align-items:center;justify-content:center;padding:1rem}
.studio-box{width:min(420px,100%);background:var(--surface);border:1px solid rgba(255,255,255,.15);border-radius:8px;padding:1.5rem}
.studio-box h2,.studio-header h1{font-family:var(--heading);margin:0 0 1rem}
.studio-field,.s-input{width:100%;border:1px solid rgba(255,255,255,.16);background:rgba(0,0,0,.25);color:var(--text);border-radius:7px;padding:.85rem}
.studio-btn,.s-submit{width:100%;background:var(--accent);color:#120d0a;margin-top:1rem}
.studio-cancel{border:0;background:none;color:var(--muted);margin-top:1rem}
.studio-panel{flex-direction:column;background:var(--bg)}
.studio-body{padding:1.5rem;overflow:auto;max-width:980px;width:100%;margin:0 auto}
.studio-section-title{color:var(--accent2);font-weight:900;text-transform:uppercase}
.upload-form,.manage-list{display:grid;gap:1rem}
.form-row{display:grid;grid-template-columns:1fr 2fr;gap:1rem}
.file-drop{position:relative;border:1px dashed rgba(255,255,255,.25);border-radius:8px;padding:1.2rem;text-align:center;color:var(--muted);background:rgba(255,255,255,.04)}
.file-drop input{position:absolute;inset:0;opacity:0;cursor:pointer}
.file-drop.drag{border-color:var(--accent);color:var(--accent)}
.form-msg{min-height:1.5rem;color:var(--muted)}
.manage-item{display:grid;grid-template-columns:auto 1fr auto;gap:1rem;align-items:center;border-bottom:1px solid rgba(255,255,255,.1);padding:.8rem 0}
.manage-del{color:var(--danger)}
@media(max-width:680px){.hero{padding:1rem}.section-head{display:block}.motifs{text-align:left}.form-row,.ep-item,.manage-item{grid-template-columns:1fr}.reader-controls{width:calc(100% - 1rem);justify-content:space-between}.reader-nav{padding:.65rem}.hero-actions{display:grid}}
</style>
</head>
<body>
<section class="hero" id="top">
  <div class="hero-bg"></div><div class="grain"></div>
  <div class="hero-content">
    <div class="tagline">${esc(theme.tagline)}</div>
    <h1 id="logoClick">${title}</h1>
    <p class="subtitle">${esc(theme.subtitle)}</p>
    <div class="hero-actions">
      <button class="btn" onclick="scrollToEpisodes()">${esc(theme.cta || "Read the Story")}</button>
      <a class="btn secondary" href="#episodes">${esc(theme.episodeLabel || "Episodes")}</a>
    </div>
  </div>
</section>
<section class="quote-strip">
  <blockquote>${esc(theme.introQuote)}</blockquote>
  <p>${esc(theme.introAttribution)}</p>
</section>
<main class="episodes" id="episodes">
  <div class="section-head">
    <h2>${esc(theme.episodeLabel || "Episodes")}</h2>
    <div class="motifs">${motifs}</div>
  </div>
  <div class="ep-list" id="epList"><div class="ep-empty">${esc(theme.emptyState || "No episodes published yet.")}</div></div>
</main>
<footer class="brand-footer"><img src="./${logoFile}" alt="SOUL Productions logo" /> <span>${author ? `by ${author} · ` : ""}Made with Story-Bildr by SOUL Productions</span></footer>

<div class="reader-overlay" id="readerOverlay">
  <div class="reader-topbar">
    <strong id="readerTitle">-</strong>
    <button class="reader-close" onclick="closeReader()">Close</button>
  </div>
  <div class="reader-stage" id="readerStage">
    <div class="reader-loading" id="readerLoading">Opening episode...</div>
    <canvas id="pdfCanvas"></canvas>
    <div class="reader-controls">
      <button class="reader-nav" id="prevPageBtn" onclick="prevPage()">Prev</button>
      <span id="pageStatus">Page - / -</span>
      <button class="reader-nav" id="nextPageBtn" onclick="nextPage()">Next</button>
    </div>
  </div>
</div>

<div class="studio-overlay" id="studioGate">
  <div class="studio-box">
    <h2>${esc(theme.studioTitle || "Writer's Studio")}</h2>
    <p style="color:var(--muted)">Enter the private studio password.</p>
    <input class="studio-field" type="password" id="pwInput" placeholder="Password" onkeydown="if(event.key==='Enter')checkPw()" />
    <button class="studio-btn" onclick="checkPw()">Enter</button>
    <div class="form-msg" id="pwErr"></div>
    <button class="studio-cancel" onclick="closeGate()">cancel</button>
  </div>
</div>

<div class="studio-panel" id="studioPanel">
  <div class="studio-header">
    <h1>${esc(theme.studioTitle || "Writer's Studio")}</h1>
    <button class="studio-exit" onclick="exitStudio()">Exit Studio</button>
  </div>
  <div class="studio-body">
    <p class="studio-section-title">${esc(theme.addEpisodeLabel || "Add an Episode")}</p>
    <div class="upload-form">
      <div class="form-row">
        <input class="s-input" type="number" id="epNum" min="1" placeholder="Episode No." />
        <input class="s-input" type="text" id="epTitle" placeholder="Title" />
      </div>
      <input class="s-input" type="text" id="epPart" placeholder="Part / Subtitle (optional)" />
      <div class="file-drop" id="fileDrop">
        <input type="file" accept="application/pdf" id="pdfInput" onchange="onFileSelect(this)" />
        <p>Click or drag a PDF here</p><p id="fileName"></p>
      </div>
      <button class="s-submit" onclick="saveEpisode()">Save Episode</button>
      <div class="form-msg" id="formMsg"></div>
    </div>
    <p class="studio-section-title">${esc(theme.manageEpisodeLabel || "Manage Episodes")}</p>
    <div class="manage-list" id="manageList"></div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"><\/script>
<script type="module">
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const STUDIO_PASS = ${js(input.studioPassword)};
const SUPABASE_URL = ${js(input.supabaseUrl)};
const SUPABASE_ANON_KEY = ${js(input.supabaseAnonKey)};
const PDF_BUCKET = ${js(names.bucket)};
const EPISODES_TABLE = ${js(names.table)};
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let episodes = [];
let currentPdfFile = null;
const PDFJS = window.pdfjsLib;
if(PDFJS) PDFJS.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
let pdfDoc = null, currentPage = 1, renderTask = null, touchStartX = 0, touchStartY = 0, resizeTimer = null;

async function loadEpisodes(){
  const { data, error } = await supabase.from(EPISODES_TABLE).select('id,num,title,part,pdf_path,created_at').order('num',{ascending:true});
  if(error){ episodes=[]; renderPublic(); renderManage(); setMsg('Supabase load failed. Check table and policies.', true); return; }
  episodes = data || []; renderPublic(); renderManage();
}
function renderPublic(){
  const list = document.getElementById('epList');
  if(!episodes.length){ list.innerHTML='<div class="ep-empty">${esc(theme.emptyState || "No episodes published yet.")}</div>'; return; }
  list.innerHTML = [...episodes].sort((a,b)=>a.num-b.num).map(ep=>\`
    <div class="ep-item" onclick="openReader(\${ep.num})">
      <span class="ep-num">Ep \${String(ep.num).padStart(2,'0')}</span>
      <div><div class="ep-title">\${escHtml(ep.title)}</div>\${ep.part ? \`<div class="ep-part">\${escHtml(ep.part)}</div>\` : ''}</div>
      <span>→</span>
    </div>\`).join('');
}
async function openReader(num){
  const ep = episodes.find(e=>e.num===num);
  if(!ep?.pdf_path){ alert('PDF not found.'); return; }
  const { data } = supabase.storage.from(PDF_BUCKET).getPublicUrl(ep.pdf_path);
  if(!data?.publicUrl || !PDFJS){ alert('PDF reader could not open.'); return; }
  document.getElementById('readerOverlay').classList.add('open');
  document.body.style.overflow='hidden';
  document.getElementById('readerTitle').textContent = 'Ep '+ep.num+' - '+ep.title;
  setReaderLoading(true);
  try{ pdfDoc = await PDFJS.getDocument({url:data.publicUrl}).promise; currentPage=1; await renderPage(currentPage); }
  catch(err){ console.error(err); alert('PDF could not be opened. Check Storage public access.'); closeReader(); }
}
async function renderPage(pageNum){
  if(!pdfDoc) return;
  if(renderTask){ try{ renderTask.cancel(); }catch{} }
  setReaderLoading(true);
  const page = await pdfDoc.getPage(pageNum);
  const stage = document.getElementById('readerStage');
  const canvas = document.getElementById('pdfCanvas');
  const ctx = canvas.getContext('2d');
  const base = page.getViewport({scale:1});
  const fit = Math.min((stage.clientWidth-32)/base.width,(stage.clientHeight-120)/base.height);
  const scale = Math.max(.75, Math.min(fit * window.devicePixelRatio, 2.4));
  const viewport = page.getViewport({scale});
  canvas.width = Math.floor(viewport.width); canvas.height = Math.floor(viewport.height);
  canvas.style.width = Math.floor(viewport.width/window.devicePixelRatio)+'px';
  canvas.style.height = Math.floor(viewport.height/window.devicePixelRatio)+'px';
  renderTask = page.render({canvasContext:ctx,viewport});
  await renderTask.promise.catch(()=>{});
  setReaderLoading(false); updateReaderControls();
}
function updateReaderControls(){
  const total = pdfDoc ? pdfDoc.numPages : 0;
  document.getElementById('pageStatus').textContent = 'Page '+currentPage+' / '+total;
  document.getElementById('prevPageBtn').disabled = currentPage <= 1;
  document.getElementById('nextPageBtn').disabled = currentPage >= total;
}
function setReaderLoading(show){ document.getElementById('readerLoading').style.display = show ? 'block' : 'none'; }
function nextPage(){ if(pdfDoc && currentPage < pdfDoc.numPages){ currentPage++; renderPage(currentPage); } }
function prevPage(){ if(pdfDoc && currentPage > 1){ currentPage--; renderPage(currentPage); } }
function closeReader(){ document.getElementById('readerOverlay').classList.remove('open'); document.body.style.overflow=''; pdfDoc=null; currentPage=1; }
function openGate(){ document.getElementById('studioGate').classList.add('open'); setTimeout(()=>document.getElementById('pwInput').focus(),50); }
function closeGate(){ document.getElementById('studioGate').classList.remove('open'); document.getElementById('pwErr').textContent=''; }
function checkPw(){ if(document.getElementById('pwInput').value===STUDIO_PASS){ closeGate(); openStudio(); } else { document.getElementById('pwErr').textContent='Wrong password.'; } }
function openStudio(){ document.getElementById('studioPanel').classList.add('open'); document.body.style.overflow='hidden'; renderManage(); }
function exitStudio(){ document.getElementById('studioPanel').classList.remove('open'); document.body.style.overflow=''; }
function onFileSelect(input){ currentPdfFile = input.files?.[0] || null; document.getElementById('fileName').textContent = currentPdfFile ? currentPdfFile.name : ''; }
function setMsg(text,isError=false){ const msg=document.getElementById('formMsg'); if(msg){ msg.style.color = isError ? 'var(--danger)' : 'var(--accent2)'; msg.textContent=text; } }
async function saveEpisode(){
  const num = parseInt(document.getElementById('epNum').value);
  const title = document.getElementById('epTitle').value.trim();
  const part = document.getElementById('epPart').value.trim();
  if(!num||num<1) return setMsg('Please enter a valid episode number.',true);
  if(!title) return setMsg('Please enter a title.',true);
  if(!currentPdfFile) return setMsg('Please select a PDF file.',true);
  setMsg('Uploading episode...');
  const existing = episodes.find(e=>e.num===num);
  const safeName = currentPdfFile.name.replace(/[^a-z0-9._-]/gi,'-').toLowerCase();
  const pdfPath = 'episodes/ep-'+String(num).padStart(2,'0')+'-'+Date.now()+'-'+safeName;
  const { error: uploadError } = await supabase.storage.from(PDF_BUCKET).upload(pdfPath,currentPdfFile,{contentType:'application/pdf',upsert:false});
  if(uploadError){ console.error(uploadError); return setMsg('Upload failed. Check bucket and policies.',true); }
  const { error: dbError } = await supabase.from(EPISODES_TABLE).upsert({num,title,part,pdf_path:pdfPath},{onConflict:'num'});
  if(dbError){ console.error(dbError); return setMsg('PDF uploaded, but database save failed.',true); }
  if(existing?.pdf_path) await supabase.storage.from(PDF_BUCKET).remove([existing.pdf_path]);
  setMsg('Episode '+num+' uploaded.');
  document.getElementById('epNum').value=''; document.getElementById('epTitle').value=''; document.getElementById('epPart').value=''; document.getElementById('pdfInput').value=''; document.getElementById('fileName').textContent=''; currentPdfFile=null;
  await loadEpisodes();
}
async function deleteEpisode(num){
  if(!confirm('Delete Episode '+num+'?')) return;
  const ep = episodes.find(e=>e.num===num);
  const { error } = await supabase.from(EPISODES_TABLE).delete().eq('num',num);
  if(error){ console.error(error); alert('Delete failed. Check table policies.'); return; }
  if(ep?.pdf_path) await supabase.storage.from(PDF_BUCKET).remove([ep.pdf_path]);
  await loadEpisodes();
}
function renderManage(){
  const list = document.getElementById('manageList'); if(!list) return;
  if(!episodes.length){ list.innerHTML='<p style="color:var(--muted)">No episodes yet.</p>'; return; }
  list.innerHTML = [...episodes].sort((a,b)=>a.num-b.num).map(ep=>\`
    <div class="manage-item"><strong>Ep \${String(ep.num).padStart(2,'0')}</strong><span>\${escHtml(ep.title)}</span><button class="manage-del" onclick="deleteEpisode(\${ep.num})">Delete</button></div>\`).join('');
}
function scrollToEpisodes(){ document.getElementById('episodes').scrollIntoView({behavior:'smooth'}); }
function escHtml(value){ return String(value||'').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch])); }
let logoClicks=0, logoTimer=null;
document.getElementById('logoClick').addEventListener('click',()=>{ logoClicks++; clearTimeout(logoTimer); logoTimer=setTimeout(()=>logoClicks=0,1200); if(logoClicks>=5){ logoClicks=0; openGate(); }});
document.getElementById('fileDrop').addEventListener('dragenter',e=>{e.preventDefault();e.currentTarget.classList.add('drag')});
document.getElementById('fileDrop').addEventListener('dragover',e=>e.preventDefault());
document.getElementById('fileDrop').addEventListener('dragleave',e=>e.currentTarget.classList.remove('drag'));
document.getElementById('fileDrop').addEventListener('drop',e=>e.currentTarget.classList.remove('drag'));
document.addEventListener('keydown',e=>{ if(e.key==='Escape'){ closeReader(); closeGate(); } if(document.getElementById('readerOverlay').classList.contains('open')){ if(e.key==='ArrowRight') nextPage(); if(e.key==='ArrowLeft') prevPage(); }});
document.getElementById('readerStage').addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX;touchStartY=e.changedTouches[0].clientY;},{passive:true});
document.getElementById('readerStage').addEventListener('touchend',e=>{ const dx=e.changedTouches[0].clientX-touchStartX, dy=e.changedTouches[0].clientY-touchStartY; if(Math.abs(dx)>60 && Math.abs(dx)>Math.abs(dy)){ dx<0 ? nextPage() : prevPage(); }},{passive:true});
window.addEventListener('resize',()=>{ if(pdfDoc){ clearTimeout(resizeTimer); resizeTimer=setTimeout(()=>renderPage(currentPage),180); }});
window.openReader=openReader; window.closeReader=closeReader; window.nextPage=nextPage; window.prevPage=prevPage; window.checkPw=checkPw; window.closeGate=closeGate; window.exitStudio=exitStudio; window.onFileSelect=onFileSelect; window.saveEpisode=saveEpisode; window.deleteEpisode=deleteEpisode; window.scrollToEpisodes=scrollToEpisodes;
loadEpisodes();
<\/script>
</body>
</html>`;
}
